/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "首页",
  "description": "playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "个人博客",
        "tagline": "这是一个使用 VuePress 来搭建的个人博客。",
        "actionText": "查看博客 →",
        "actionLink": "/blog/",
        "features": [
          {
            "title": "简介明了",
            "details": "一个很简单的 demo，相信以你的实力可以快速的看懂。"
          },
          {
            "title": "具体作用",
            "details": "主要是给你提供一个具体的案例，让你在使用 VuePress 能够更快速的搭建个人博客网站，"
          }
        ],
        "footer": "Copyright © 2022-present, TalkingData outtathewoods8@gmail.com."
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4ee6494c",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "ryannnnn的个人博客",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/ryannnnnwang"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/3087907771127559"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "欢迎学习",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "学前必读",
            "path": "/"
          }
        ]
      },
      {
        "title": "基础学习",
        "path": "/handbook/ConditionalTypes",
        "collapsable": false,
        "children": [
          {
            "title": "条件类型",
            "path": "/handbook/ConditionalTypes"
          },
          {
            "title": "泛型",
            "path": "/handbook/Generics"
          }
        ]
      }
    ]
  }
}